import { Company, Vacancy } from "@/types";

export const MOCK_COMPANIES: Company[] = [
  {
    id: "comp_1",
    name: "Kaspi.kz",
    logo: "🔴",
    description: "Қазақстандағы ең ірі финтех компаниясы.",
    industry: "Fintech",
    location: "Алматы",
    size: "1000+",
    contacts: { phone: "+7 727 258 59 55", website: "https://kaspi.kz" },
  },
  {
    id: "comp_2",
    name: "Kolesa Group",
    logo: "🚗",
    description: "IT компания, Қазақстанның үздік өнімдерін жасайды.",
    industry: "IT",
    location: "Алматы",
    size: "500-1000",
    contacts: { website: "https://kolesa.kz" },
  },
  {
    id: "comp_3",
    name: "Air Astana",
    logo: "✈️",
    description: "Қазақстанның ұлттық әуе тасымалдаушысы.",
    industry: "Aviation",
    location: "Астана",
    size: "1000+",
    contacts: { phone: "+7 7172 58 44 77", website: "https://airastana.com" },
  },
  {
    id: "comp_4",
    name: "Magnum",
    logo: "🛒",
    description: "Ең ірі бөлшек сауда желісі.",
    industry: "Retail",
    location: "Алматы",
    size: "10000+",
    contacts: { website: "https://magnum.kz" },
  },
  {
    id: "comp_5",
    name: "Halyk Bank",
    logo: "🏛️",
    description: "Сенімді қаржы ұйымы.",
    industry: "Banking",
    location: "Алматы",
    size: "10000+",
    contacts: { website: "https://halykbank.kz" },
  }
];

export const MOCK_VACANCIES: Vacancy[] = [
  {
    id: "vac_1",
    title: "Senior React/Next.js Developer",
    companyId: "comp_1",
    salary: { min: 1200000, max: 1800000, currency: "KZT" },
    location: "Алматы",
    type: "hybrid",
    category: "it",
    description: "Kaspi өнімдерін дамытатын командаға тәжірибелі React маман іздейміз.",
    requirements: ["React 18+", "Next.js 14", "TypeScript", "Zustand", "Tailwind CSS"],
    createdAt: new Date().toISOString(),
    emoji: "💳",
  },
  {
    id: "vac_2",
    title: "Product Manager",
    companyId: "comp_2",
    salary: { min: 900000, max: 1200000, currency: "KZT" },
    location: "Алматы / Қашықтан",
    type: "remote",
    category: "marketing",
    description: "Kolesa.kz платформасының жаңа мүмкіндіктерін басқару.",
    requirements: ["Agile/Scrum", "A/B testing", "Jira", "Уақытты басқару"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    emoji: "📊",
  },
  {
    id: "vac_3",
    title: "Data Analyst",
    companyId: "comp_3",
    salary: { min: 700000, max: 900000, currency: "KZT" },
    location: "Астана",
    type: "full",
    category: "it",
    description: "Авиация саласындағы деректерді талдау және бизнес шешімдерге көмектесу.",
    requirements: ["SQL", "Python", "Power BI", "Аналитикалық ойлау"],
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    emoji: "📈",
  },
  {
    id: "vac_4",
    title: "UX/UI Designer",
    companyId: "comp_4",
    salary: { min: 600000, max: 850000, currency: "KZT" },
    location: "Алматы",
    type: "part",
    category: "design",
    description: "Magnum мобильді қосымшасының дизайнын жақсарту.",
    requirements: ["Figma", "UI/UX принциптері", "Прототиптеу", "iOS/Android guidelines"],
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    emoji: "🎨",
  },
  {
    id: "vac_5",
    title: "Бухгалтер",
    companyId: "comp_5",
    salary: { min: 400000, max: 550000, currency: "KZT" },
    location: "Астана",
    type: "full",
    category: "finance",
    description: "Банк саласындағы бухгалтерлік есепті жүргізу.",
    requirements: ["1С Бухгалтерия", "Қаржылық заңнама", "Excel", "Нақтылық"],
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    emoji: "💰",
  },
  {
    id: "vac_6",
    title: "DevOps Engineer",
    companyId: "comp_1",
    salary: { min: 1400000, currency: "KZT" },
    location: "Алматы",
    type: "hybrid",
    category: "it",
    description: "Инфрақұрылымды басқару және CI/CD процестерін оңтайландыру.",
    requirements: ["Kubernetes", "Docker", "GitLab CI", "Linux", "Terraform"],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    emoji: "⚙️",
  },
  {
    id: "vac_7",
    title: "SMM Manager",
    companyId: "comp_4",
    salary: { min: 350000, max: 500000, currency: "KZT" },
    location: "Алматы",
    type: "full",
    category: "marketing",
    description: "Magnum әлеуметтік желілерін жүргізу (Instagram, TikTok).",
    requirements: ["Копирайтинг", "Мобилография", "Таргет негіздері", "Креативтілік"],
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    emoji: "📱",
  },
  {
    id: "vac_8",
    title: "Backend Go Developer",
    companyId: "comp_2",
    salary: { min: 1000000, max: 1500000, currency: "KZT" },
    location: "Қашықтан",
    type: "remote",
    category: "it",
    description: "Highload жобалар үшін микросервистер әзірлеу.",
    requirements: ["Golang", "PostgreSQL", "Redis", "gRPC", "Kafka"],
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    emoji: "🐹",
  }
];
